### ISSUE TITLE
First string

### ISSUE THREAD

**Issue by MarQua** [WaldemarBjornstrom/docx_search#1]
The module doesn't work properly if you are looking for the FIRST string of the document.

Enclosed the file
[prova.docx](https://github.com/WaldemarBjornstrom/docx_search/files/6853465/prova.docx)

This is the code:
import docx_search
print(docx_search.run("PProva", "C:\\BOM\\"))

**Comment by oven-lab** [comment]
Thank you for your feedback! I am looking into it right now!

**Comment by oven-lab** [comment]
@MarQua As far as i can tell this is a problem with the document formatting in word. In the xml file some words were split into multiple words. But i will absolutely see if this is something that the code may be able to fix.

<w:r>
<w:rPr>
<w:lang w:val="en-US"/>
</w:rPr>
**<w:t>P</w:t>**
</w:r>
<w:bookmarkStart w:name="_GoBack" w:id="0"/>
<w:bookmarkEnd w:id="0"/>
<w:r w:rsidR="004F64EF">
<w:rPr>
<w:lang w:val="en-US"/>
</w:rPr>
**<w:t>Prova</w:t>**
</w:r>

**Comment by oven-lab** [comment]
Fixed this issue in v1.0.1
